version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/99-my.ini
      - ./:/var/www/html/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8585:80"
      - "446:443"
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/99-my.ini
      - ./.docker/php/php.ini:/etc/php/8.1/cli/conf.d/99-my.ini
#      - ./.docker/php/docker.conf:/etc/php/810/fpm/pool.d/docker.conf
#      - ./.docker/php/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
#      - ./.docker/php/zz-docker.conf:/etc/php/8.1/fpm/pool.d/zz-docker.conf
    depends_on:
      - mysql
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 0
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_INTL: 1
      XDEBUG_CONFIG: "client_host=172.17.0.1 log=/tmp/xdebug.log"
      PHP_IDE_CONFIG: "serverName=localhost"
#      STARTUP_COMMAND_1: composer install
#      STARTUP_COMMAND_2: NETTE_DEBUG=1 php bin/console migrations:migrate --no-interaction --allow-no-migration
#      STARTUP_COMMAND_3: NETTE_DEBUG=1 php bin/console doctrine:fixtures:load --no-interaction
  mysql:
    container_name: mysql
    restart: always
    image: mariadb
    user: "root"
    ports:
      - "3312:3306"
    volumes:
      - .docker/mysql/data:/var/lib/mysql
#      - .docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#      - .docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    #      - ./tmp/db:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  adminer:
    image: dockette/adminer:dg
    ports:
      - 8383:80

volumes:
  database-volume:
